### ISSUE TITLE
[BUG] Additional Modules Not Reconciled After Kyma Environment Creation

### ISSUE THREAD

**Issue by jtucci** [SAP/crossplane-provider-btp#116]
**Describe the bug**
After successfully creating a Kyma environment with custom modules specified in the configuration, additional modules added afterward are not reconciled and are not reflected externally.

**Tested with Provider Version**
v1.0.3

**To Reproduce**
1. Create a Kyma environment with a custom module list containing telemetry and keda.
```yaml
spec:
  forProvider:
    parameters:
      ...
      modules:
        list:
          - name: telemetry
          - name: keda
```
2. After the Kyma environment is created successfully, add additional modules (e.g., istio, btp-operator) to the list in the spec.
```yaml
spec:
  forProvider:
    parameters:
      ...
      modules:
        list:
          - name: telemetry
          - name: keda
          - name: istio
          - name: btp-operator
```
3. Observe that the newly added modules are not reconciled or added externally.

**Expected behavior**
The newly added modules should be reconciled and reflected externally.
