### ISSUE TITLE
[TASK] Check TF Subscription Resource for being a better implementation

### ISSUE THREAD

**Issue by sdischer-sap** [SAP/crossplane-provider-btp#117]
**Is your feature request related to a problem? Please describe.**
In a previous inner source ticket we discovered that the SaaS Provisiong API (which is used for the `Subscription` kind has some limitation. Some services seem to require some extra data called `userInfo` which can't be passed over that API, but which apparently is supplied when using the BTP cockpit. 

**Describe the solution you'd like**
If this limitation does not apply for the btp terraform provider we can consider to exchange the used implementation to upjetting the related [tf resource](https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount_subscription).

Before doing that we should check if we can provision instances like that successfully using terraform directly. 
Scope for this ticket is only to provide some feedback on whether this is feasible or not.

**Additional context**
Failing resource from the previous ticket. 
```
apiVersion: account.btp.sap.crossplane.io/v1alpha1
kind: Subscription
metadata:
  name: 'eu10-preprod-provider-custom-domain-manager-instance'
spec:
  deletionPolicy: Orphan
  cloudManagementRef:
    name: 'eu10-preprod-provider-cloud-management'
  forProvider:
    appName: custom-domain-manager
    planName: standard
  providerConfigRef:
    name: 'eu10-preprod-cf-provider'
```
