### ISSUE TITLE
`Directory` resource unhealthy state

### ISSUE THREAD

**Issue by GenosseOtt** [SAP/crossplane-provider-btp#154]
### When did it (start to) happen?

2025-03-31T08:33:45Z

### In case of 'Other' provider, please specify

btp

### Which provider version do you use? 

1.0.3

### What happened?

I created a new `directory`. I was created and I can update it. however it never is in `synced` state:
```
NAME       READY   SYNCED   EXTERNAL-NAME                          AGE
ben-test   True    False    849bcd92-9fc3-46d8-b004-9a6ddd39329a   3h39m
```

### What did you expect to happen and why?

as I created the resource via openMCP managed Control Plane i would expect it to end up in a healthy state

### Please provide meaningful logs that outline the issue

```bash
❯ cat ~/.kube/mcp-mdi-mcp.yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: <obfuscated>
  name: mcp-project-mdi-iad--ws-mdi-ops-mdi-mcp
contexts:
- context:
    cluster: mcp-project-mdi-iad--ws-mdi-ops-mdi-mcp
    namespace: default
    user: openmcp
  name: mcp-project-mdi-iad--ws-mdi-ops-mdi-mcp--openmcp
current-context: mcp-project-mdi-iad--ws-mdi-ops-mdi-mcp--openmcp
kind: Config
```

### Please provide meaningful manifests that outline the issue

```yaml
❯ cat directory.yaml
apiVersion: account.btp.sap.crossplane.io/v1alpha1 # string
kind: Directory
metadata:
  name: ben-test
  namespace: btp-mdi-dev
spec:
  deletionPolicy: Orphan
  forProvider:
    description: test for ben
    directoryAdmins:
      - xxx@sap.com
      - yyy@sap.com
      - zzz@sap.com
    displayName: ben-test-bar
  providerConfigRef:
    name: account-provider-config
```

### How can we reproduce the issue (concisely and precisely)?

1. create resource
2. look at resource status
