### ISSUE TITLE
[FEATURE] Module Management for Kyma

### ISSUE THREAD

**Issue by sdischer-sap** [SAP/crossplane-provider-btp#166]
**Context**
With 

**Scope**

**Out of scope**
If needed, describe what parts of a feature can be ignored for now.

_Hint_: Smaller feature wishes tend to be implemented and shipped quicker!

**Technical Steps** 
(Optional) - outline steps for contributors to give implementation guidance and allow transparent technical discussions.

**Workarounds & Alternatives**
Describe, if possible, how you are solving this problem today.

**Additional context**

**Comment by maximilianbraun** [comment]
More about Kyma Modules:
https://help.sap.com/docs/btp/sap-business-technology-platform/kyma-modules / https://help.sap.com/docs/btp/sap-business-technology-platform/enable-and-disable-kyma-module#loio1b548e9ad4744b978b8b595288b0cb5c
Most interesting might be the implementation in kyma cli (https://github.com/kyma-project/cli/blob/4c880eacbc98eaad40d5e4d721982060871fd267/internal/cmd/alpha/module/add.go#L16)

Or one can have a look into the kyma dashboard / the crd in a kyma cluster.

**Comment by sdischer-sap** [comment]
@GenosseOtt this one is good to go to refinement once approved.

**Comment by Lasserich** [comment]
So the way this works:
- Every Kyma Cluster has an Operator `kymas.operator.kyma-project.io` running 
- In its spec there is a modules section:
```yaml
Spec:
  Channel:  fast
  Modules:
    Custom Resource Policy:  CreateAndDelete
    Managed:                 true
    Name:                    api-gateway
    Custom Resource Policy:  CreateAndDelete
    Managed:                 true
    Name:                    istio
    Custom Resource Policy:  CreateAndDelete
    Managed:                 true
    Name:                    btp-operator
    Custom Resource Policy:  CreateAndDelete
    Managed:                 true
    Name:                    cloud-manager
```

**^ This is being resolved by providing the manifest below ^**

```yaml
apiVersion: operator.kyma-project.io/v1beta2
kind: Kyma
# ...
status:
  modules:
  - channel: regular
    fqdn: kyma.project.io/module/btp-operator
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: 24bd3cbf-454a-4075-baa6-113a23fdfcd0-btp-operator-4128321918
        namespace: kcp-system
    name: btp-operator
    state: Processing
    template:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: ModuleTemplate
      metadata:
        generation: 2
        name: moduletemplate-btp-operator
        namespace: kcp-system
    version: 1.2.10
```
- Adding or removing modules here translates to them being added/removed to the cluster and UI

Each tracked module is based on one entry in .spec.modules and represents the resolved Manifest CR that is based on a given `ModuleTemplate` CR in a release channel (`ModuleReleaseMetadata`).

**Comment by Lasserich** [comment]
Implementation wise this could be handled in two ways:

**1. Add modules to the Kyma CR via `spec.forProvider.modules[]`**

```yaml
apiVersion: environment.btp.sap.crossplane.io/v1alpha1
kind: KymaEnvironment
metadata:
  name: my-kyma-instance-one
spec:
  subaccountRef:
    name: lasse-kyma-subaccount-one
  cloudManagementRef:
    name: cis-local-one
  writeConnectionSecretToRef:
    name: kyma-kubeconfig-local-one
    namespace: default
  forProvider:
    planName: azure
#  modules:
#  - cloud-manager
#  - btp-operator 
#  - api-gateway
#  - istio 
    parameters:
      region: westeurope
      machineType: Standard_D2s_v5
      autoScalerMin: 3
      autoScalerMax: 3
      administrators:
      - ...@sap.com
```

With reconciliation only when the field is provided, otherwise it should just use the standard modules (no-op from our side). 
**Pros:** Close to other parameters, closer to the Kyma Operators implementation. 
**Cons:** Deviation from standard Kyma API. 

**2. Add modules via an extra CR and DONT add it to Kyma CR**
```yaml
apiVersion: environment.btp.sap.crossplane.io/v1alpha1 #(we keep using this one here?)
kind: KymaModule
metadata:
  name: my-kyma-module-one
spec:
  kymaBindingRef:
    name: lasse-kyma-binding-one
  kymaEnvironmentRef:
    name: my-kyma-instance-one
   forProvider:
    moduleName: cloud-manager
    channel: regular
```

These should ideally be dynamically created by the KymaEnvironment/KymaBinding in a separate namespace (?) with all currently installed modules within.
**Pros:** Keeps Kyma environment implementation untouched, closer to the Operator custom resources. 
**Cons:** Added complexity going with the namespace approach. Does not feel very natural in its configuration.
