### ISSUE TITLE
[BUG] GitOps updating the composition claim does not trigger reconciliation

### ISSUE THREAD

**Issue by JayChanggithub** [SAP/crossplane-provider-btp#96]
**Describe the bug**

We encountered a strange situation where, after updating the XRD claim values in helm [repository ](https://github.tools.sap/rgm/infra-cloud-orchestrator-rgm/blob/main/k-sre-slow-us21-co/charts/values.yaml) and ensuring the composition was rendered correctly with all statuses ready, the reconciliation process was not triggered. The issue persisted until we deleted the XRD resources

**Tested with Provider Version**
```
apiServer:
  type: GardenerDedicated
btpServiceOperator:
  version: 0.6.8
externalSecretsOperator:
  version: 0.10.7
flux:
  version: 2.14.0
crossplane:
  version: 1.18.0
  providers:
    - name: btp
      version: 1.0.2
    - name: kubernetes
      version: 0.15.0
    - name: ias
      version: 0.2.0
    - name: vault
      version: 1.0.0
    - name: btp-account
      version: 0.7.6
    - name: argocd
      version: 0.9.1
```

**To Reproduce**

1. Git clone [repository](https://github.tools.sap/rgm/infra-cloud-orchestrator-rgm) and updated values.yaml to desired also create PR.
```
# from 
kymaParameters:
  region: eastus
  machineType: Standard_D8s_v5
  autoScalerMin: 3
  autoScalerMax: 4

# to 
kymaParameters:
  region: eastus
  machineType: Standard_D8s_v5
  autoScalerMin: 3
  autoScalerMax: 5
```

2. Merge to main branch to trigger fluxCD GitOps mechanism.
3. type serval commands to ensure as below. 

```
$ k get helmreleases.helm.toolkit.fluxcd.io
helmrelease   2d8h   True    Helm upgrade succeeded for release default/default-helmrelease.v11 with chart k-sre-slow-us21-co@1.0.0+9c6d1e235c9e

$ k get xrd       
xbtpsubaccounts.sre.tools.sap     True          True      2d8h
xkymaenvironments.sre.tools.sap   True          True      2d8h

$ k get kymaenvironments.sre.tools.sap k-sre-slow-us21-co(Ensure the latest values was rendered success)
$ k get kymaenvironments.environment.btp.orchestrate.cloud.sap k-sre-slow-us21-co -oyaml(Not yet changed)
```

4. Until delete xrd resources such that trigger reconciliation also waiting a moments. but these behavior will trigger delete kyma resources then create. 

```
k delete xkymaenvironments.sre.tools.sap k-sre-slow-us21-co-kn7t5
```
5. The reconciliation and processing of Kyma resources in the BTP Cockpit indicate a successful trigger. 

**Expected behavior**

It should reconcile to the latest values automatically, rather than requiring manual deletion.

**Additional context**
```
# mcp
project: iccx-sre-us21
k get workspace -n project-iccx-sre-us21 slow 
k get mcp -n project-iccx-sre-us21--ws-slow 

# GitOps Repository 
https://github.tools.sap/rgm/infra-cloud-orchestrator-rgm
```
